# -*- coding: utf-8 -*-
"""rag-basico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10L0V3Ec1b992Gylo5da3198jAH4v9Hak
"""

from dotenv import load_dotenv
import os
import re
import requests
from bs4 import BeautifulSoup
from langchain_core.documents import Document
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pypdf import PdfReader
import chromadb
from openrouter_embedding import OpenRouterEmbedding


def cargar_urls(urls):
    """Descarga páginas web y extrae el texto."""
    docs = []
    for url in urls:
        resp = requests.get(url, timeout=15)
        soup = BeautifulSoup(resp.text, "lxml")
        texto = soup.get_text()
        docs.append(Document(page_content=texto, metadata={"source": url}))
    return docs


# Create a persistent client
client = chromadb.PersistentClient(path="./chroma_db")

# Convert PDF to Text


def load_pdf(pdf_path):
    """
    Load a PDF file and convert to text documents

    Args:
        pdf_path (str): Path to PDF file

    Returns:
        list: List of document pages
    """
    reader = PdfReader(pdf_path)
    return [
        Document(page_content=page.extract_text(),
                 metadata={"page": i, "source": pdf_path})
        for i, page in enumerate(reader.pages)
    ]


def create_chunks(documents, chunk_size=800, chunk_overlap=200):
    """
    Split documents into overlapping chunks

    Args:
        documents (list): List of documents to split
        chunk_size (int): Size of each chunk in characters
        chunk_overlap (int): Number of characters to overlap between chunks

    Returns:
        list: List of text chunks
    """
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=chunk_size,
        chunk_overlap=chunk_overlap,
        length_function=len,
        is_separator_regex=False,
    )

    chunks = text_splitter.split_documents(documents)
    return chunks


# --- URL Ingestion ---

def load_url(url):
    """
    Load a single URL and convert to text documents.

    Args:
        url (str): The URL to load.

    Returns:
        list: List of LangChain Document objects.
    """
    return cargar_urls([url])


def load_urls(urls):
    """
    Load multiple URLs and convert to text documents.

    Args:
        urls (list[str]): List of URLs to load.

    Returns:
        list: List of LangChain Document objects from all URLs.
    """
    return cargar_urls(urls)


# --- Ingest URLs from Donostia.eus ---

urls = [
    "https://www.donostia.eus/es/avisos/afectaciones-trafico-gros-junio-6",
    "https://www.donostia.eus/es/avisos/san-bartolome-reunion-cidadania-8-junio",
    "https://www.donostia.eus/es/avisos/temporada-playas",
]

print("Loading URLs...")
url_docs = load_urls(urls)
print(f"Loaded {len(url_docs)} documents from {len(urls)} URLs")

# Chunk the loaded documents
chunks = create_chunks(url_docs)
print(f"Created {len(chunks)} chunks")

# Limpiar espacios extra del HTML
def limpiar(texto):
    return re.sub(r"\s+", " ", texto).strip()

# Create a collection with OpenRouter embeddings

# API Key from Env
load_dotenv()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

embedding_function = OpenRouterEmbedding(OPENROUTER_API_KEY)

collection_name = "donostia_avisos"

# Delete existing collection if re-running
if collection_name in [c.name for c in client.list_collections()]:
    client.delete_collection(collection_name)

collection = client.create_collection(
    name=collection_name,
    embedding_function=embedding_function
)

# Add chunks to collection
collection.add(
    documents=[limpiar(chunk.page_content) for chunk in chunks],
    metadatas=[chunk.metadata for chunk in chunks],
    ids=[str(i) for i in range(len(chunks))]
)

print(f"Collection '{collection_name}' size: {collection.count()}")

# --- Query the collection ---

query_text = "¿Qué cortes de tráfico hay en Gros?"

results = collection.query(
    query_texts=[query_text],
    n_results=3
)

# Display the results
print(f"\nQuery: {query_text}\n")
for i, doc in enumerate(results['documents'][0]):
    print(f"Result {i+1}:")
    print(f"Content: {doc[:300]}...")
    print(f"Source: {results['metadatas'][0][i].get('source', 'N/A')}")
    print("-" * 20)
